apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trino.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "trino.fullname" . }}
  namespace: {{ .Release.Namespace }}