{{- if and .Values.openshift.enabled .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "trino.fullname" . }}-ui
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    component: coordinator
spec:
  {{- if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "trino.fullname" . }}-coordinator
    weight: 100
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    {{- if .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}